name: Deploy to server

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  Deply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@v2
        
      - name: Deploy
        uses: burnett01/rsync-deployments@5.2
        with:
         switches: -avzr --delete --exclude=".git*" --exclude="Sass/*" --exclude="Scripts/ts/*"
         path: /
         remote_path: ${{secrets.TARGET_MAIN_DIR}}
         remote_host: ${{secrets.SSH_HOSTNAME}}
         remote_port: ${{secrets.SSH_PORT}}
         remote_user: ${{secrets.SSH_USERNAME}}
         remote_key: ${{secrets.SSH_PRIVATE_KEY}}